const actionTypes = {
  LOGOUT: 'LOGOUT',
  SET_APP_STATE: 'SET_APP_STATE',
  SET_IS_CONNECTED: 'SET_IS_CONNECTED',
  SET_NEXT_VERSION: 'SET_NEXT_VERSION',
  SET_SKIP_VERSION: 'SET_SKIP_VERSION',
  SET_FEATURE_STATUS: 'SET_FEATURE_STATUS',
  SET_UPDATE_MESSAGE: 'SET_UPDATE_MESSAGE',
  SET_MAINTENANCE_STATUS: 'SET_MAINTENANCE_STATUS',
  SET_MAINTENANCE_MESSAGE: 'SET_MAINTENANCE_MESSAGE',
  SET_FORCE_UPDATE_STATUS: 'SET_FORCE_UPDATE_STATUS',
  SETTING_ONBOARDING_STATE: 'SETTING_ONBOARDING_STATE',
  SET_OFFLINE_NOTICE_STATUS: 'SET_OFFLINE_NOTICE_STATUS',
  SET_OPTIONAL_UPDATE_STATUS: 'SET_OPTIONAL_UPDATE_STATUS'
};

export default actionTypes;
