const actionTypes = {
  SET_LIST_ROOM: 'SET_LIST_ROOM',
  SET_DATA_CHART: 'SET_DATA_CHART',
  SET_WAITING_ROOM: 'SET_WAITING_ROOM',
  SET_DATA_LAST_WINNER: 'SET_DATA_LAST_WINNER',
  SET_DATA_LIST_BIDDER: 'SET_DATA_LIST_BIDDER',
};

export default actionTypes;
