// V1
const actionTypes = {
  LOGOUT: 'LOGOUT',
  SET_NOTIFICATION_DATA: 'SET_NOTIFICATION_DATA',
  SET_NOTIFICATION_TOKEN: 'SET_NOTIFICATION_TOKEN',
  SET_PUSH_NOTIFICATION_DATA: 'SET_PUSH_NOTIFICATION_DATA',
  CLEAR_PUSH_NOTIFICATION_DATA: 'CLEAR_PUSH_NOTIFICATION_DATA',
};

export default actionTypes;
