const actionTypes = {
  SET_CART_KEY: 'SET_CART_KEY',
  SET_CART_ROOM: 'SET_CART_ROOM',
  CLEAR_CART_KEY: 'CLEAR_CART_KEY',
  SET_PAYMENT_TYPE: 'SET_PAYMENT_TYPE',
  SET_SELECTED_SHIPPING: 'SET_SELECTED_SHIPPING',
};

export default actionTypes;
